exclude: [README.md, resources/src]
title: Semantics
email: e.shutova@uva.nl
description: > 
    Here you will find additional material for semantics course offered at UvA.
url: "https://cl-illc.github.io" # the base hostname & protocol for your site
baseurl: "/semantics-2025" # the subpath of your site, e.g. /blog/
github_username:  cl-illc
#paginate: 3

# useful links
illc_url: http://www.illc.uva.nl
uva_url: http://www.uva.nl/en/home

# Build settings
markdown: kramdown

